# Cleaning in ML dataset
1) Finding missing values and filled them By(mean, median,mode)
2) Finding Inconsistencies and removing/ converting them in standard form
3) Finding Duplicate Values and removing them

In [ ]:
!pip install pandas
!pip install openpyxl

In [2]:
import pandas as pd
df = pd.read_excel("C:\\Users\\92324\\Desktop\\ML_from_Sratch\\ML_from_Scratch\\sales_data.xlsx")

In [3]:
df.head(110)

        Date    Product  Units Sold  Revenue Region
0 2025-01-01  Product A          10      100  North
1 2025-01-02  Product B          15      150  South
2 2025-01-03  Product C           7       70   East
3 2025-01-04  Product A          20      200   West
4 2025-01-05  Product B          25      250  North
5 2025-01-06  Product C          12      120  South
6 2025-01-07  Product A          30      300   East
7 2025-01-08  Product B          35      350   West
8 2025-01-09  Product C          14      140  North
9 2025-01-10  Product A          40      400  South

In [4]:
data = {
    'product':['Laptop', 'Mouse', 'Keyboard'],
    'Price': [1000,25,50],
    'Stock': [50, 200, 150]
}

product = pd.DataFrame(data)
product.to_csv('products.csv', index = False)

In [5]:
missing_data = df.isnull().sum()
print("Missing Data:")
missing_data

Missing Data:

Date          0
Product       0
Units Sold    0
Revenue       0
Region        0
dtype: int64

In [6]:
df.dtypes

Date          datetime64[us]
Product                  str
Units Sold             int64
Revenue                int64
Region                   str
dtype: object

In [7]:
df['Revenue'] = df['Revenue'].astype(float)

In [8]:
df.dtypes

Date          datetime64[us]
Product                  str
Units Sold             int64
Revenue              float64
Region                   str
dtype: object

## Inconsistencies in dataset

In [11]:
# find incosistencies
unique_values = df["Region"].unique()
unique_values

<StringArray>
['North', 'South', 'East', 'West']
Length: 4, dtype: str

In [ ]:
# Lets wast is undesired value
df = df[df["Region"] != 'West']

In [13]:
df["Region"].unique()

<StringArray>
['North', 'South', 'East']
Length: 3, dtype: str

## Duplicates in dataset

In [14]:
duplicates = df.duplicated()
df[duplicates]

Empty DataFrame
Columns: [Date, Product, Units Sold, Revenue, Region]
Index: []

In [15]:
# in our case no duplicate lets suppose if we have then remove by following way
df.drop_duplicates(inplace = True)